### ISSUE TITLE
TLE.js violates typing and causes full crash

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#56] opened 2022-02-28 15:46 UTC
Haven't yet figured out the root cause of this but want to document what I noticed. It seems like filtering on Sector=Civil breaks everything with some sort of TypeError. I noticed that selecting Commercial first and then Commercial || Civil is just fine, but if I then remove Commercial it crashes. This does not cause a crash on the landing page, but does in Orbits, Orbits (2D), or Origin -- which all at the moment access the `orbits.ts` code!

List of known crashes:
- [ ] filtering on sector == civil
- [ ] selecting random satellites on 2D view (it happens seemingly randomly on selection change)

**Comment by Bone008** [comment] 2022-02-28 15:54
Noticed this happening too every now and then. For some satellites `getOrbitsECI` returns undefined entries in the coordinates I believe, so we should (a) handle failure to calculate trajectories more gracefully and (b) find out why some TLEs cause this problem :)

**Comment by sahilshahpatel** [comment] 2022-03-05 17:06
Problem seems internal to TLE.js. My recommended solution is to remove the TLE.js dependency and see if we can instead use the geodetic coordinates from satellite.js to create our own ground tracks.

For now I made a bandaid fix which just returns an empty list if there are errors. This does result in the weird consequence of fewer orbits rendering than you would expect otherwise, so it isn't a permanent solution.

**Comment by sahilshahpatel** [comment] 2022-03-05 17:07
@Bone008 I could not reproduce the bug you had with the 2D ground tracks changing when you selected an orbit. If you have a chance to see if it is still happening to you that would be cool!

**Comment by Bone008** [comment] 2022-03-06 12:43
> @Bone008 I could not reproduce the bug you had with the 2D ground tracks changing when you selected an orbit. If you have a chance to see if it is still happening to you that would be cool!

It's still reproducible for me but happens very randomly, you can test it for example when selecting `1964-063C` (which is visible in the default filter) and toggling the "United States" filter on and off to trigger re-renders. Sometimes the entire line just jumps maybe 50px left/right.

(I would post screenshots but I think the train wifi blocks or breaks file uploading somehow ...)

**Comment by Bone008** [comment] 2022-03-06 12:55
My assumption is that the jump happens because the orbits traces are quite extreme and the library does some wonky stuff, which is slightly different wonky depending on which exact start time (`Date.now()`) is passed in on each render.

I would suggest as a workaround either:

(a) Use a fixed time for calculations (`Date.now()` at page load time for example)
(b) Cache the trace & orbit results for each satellite and never calculate them more than once while the page is open. We can just use a global mapping from COSPAR IDs to the traces. This also helps performance :)

**Comment by Bone008** [comment] 2022-03-06 13:58
@sahilshahpatel  More severely, a full crash sometimes still happens in the globe view because of this line:

https://github.com/Bone008/orbiteye/blob/da3fc35f215b75ee5b23742d33650903fb75fa57/src/util/orbits.ts#L72-L73

Since the loop sometimes skips over filling out the `coordinates` array with Vectors, the returned array may contain undefined values, which crashes the calling code. I don't know what the "right" way to handle the error case is when `propagate` returns false, but I guess we should return an empty array instead?

To reproduce, start with the default filter in globe view and filter by owner "Belgium".

**Comment by Bone008** [comment] 2022-03-15 23:57
TLE-related crashes seem to be fully eliminated by now, closing

**Closed as completed by Bone008** 2022-03-15 23:57 UTC
Labels: bug, priority: high
